import fs from 'node:fs';
const p='public/building-ui.js';let s=fs.readFileSync(p,'utf8');
s=s.replace("let selected='building-1',level=25,query='',category='';","let selected='building-1',level=25,query='',category='',lastAltar='building-3-fire';\n const isAltar=id=>id==='building-3'||id.startsWith('building-3-');\n const pickerBuildings=()=>{let seen=false;return buildings().flatMap(b=>{if(!isAltar(b.id))return [b];if(seen)return [];seen=true;return [{...b,id:'altar',name:'祭壇'}];});};\n function altarTabs(){return `<div class=\"altar-tabs\" role=\"tablist\" aria-label=\"祭壇の属性\">${buildings().filter(b=>isAltar(b.id)).map(b=>`<button type=\"button\" role=\"tab\" id=\"tab-${b.id}\" aria-controls=\"altar-panel\" aria-selected=\"${b.id===selected}\" tabindex=\"${b.id===selected?0:-1}\" data-building=\"altar-tab\" data-id=\"${b.id}\">${b.element||'旧記録'}<small>${state().buildingProgress?.[b.id]?.[0]?'Lv.'+state().buildingProgress[b.id][0]:'未建設'}</small></button>`).join('')}</div>`;}");
s=s.replace('return `<div class="building-focus">','return `${isAltar(b.id)?altarTabs():\'\'}<div class="building-focus" ${isAltar(b.id)?`id="altar-panel" role="tabpanel" aria-labelledby="tab-${b.id}"`:""}>');
let start=s.indexOf(' function list()'),end=s.indexOf(' function page()',start);
s=s.slice(0,start)+` function list(){return pickerBuildings().filter(b=>(!category||b.category===category)&&(b.id==='altar'?buildings().filter(x=>isAltar(x.id)).some(x=>x.name.includes(query.normalize('NFKC'))):b.name.normalize('NFKC').includes(query.normalize('NFKC')))).map(b=>{const active=b.id==='altar'?isAltar(selected):b.id===selected;const count=(b.id==='altar'?buildings().filter(x=>isAltar(x.id)).flatMap(x=>state().buildingProgress?.[x.id]||[]):state().buildingProgress?.[b.id]||[]).filter(n=>n>0).length;return \`<button data-building="select" data-id="\${b.id}" class="building-option \${active?'selected':''}" aria-pressed="\${active}"><b>\${esc(b.name)}</b><small>\${count?count+(b.id==='altar'?'属性 建設済み':'棟 建設済み'):'未建設'}</small></button>\`;}).join('')||'<p class="hint">一致する施設がありません。</p>';}
`+s.slice(end);
s=s.replace('${buildings().length}種','${pickerBuildings().length}種').replace("esc(get()?.name||'')","esc(isAltar(selected)?'祭壇':get()?.name||'')");
s=s.replace("case 'select':selected=el.dataset.id;","case 'altar-tab':selected=el.dataset.id;lastAltar=selected;refresh();$('#tab-'+selected)?.focus();break;case 'select':selected=el.dataset.id==='altar'?lastAltar:el.dataset.id;");
s=s.replace("'施設を選ぶ：'+get().name+' ▾'","'施設を選ぶ：'+(isAltar(selected)?'祭壇':get().name)+' ▾'");
s=s.replace(" return {page};",` document.addEventListener('keydown',e=>{if(!e.target.matches('[data-building="altar-tab"]'))return;const tabs=[...e.target.parentElement.querySelectorAll('[role="tab"]')],i=tabs.indexOf(e.target);let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();tabs[next].click();}});
 return {page};`);
fs.writeFileSync(p,s);
let app=fs.readFileSync('public/app.js','utf8');app=app.replace("function renderPage(){","function renderPage(){$('.main').dataset.scene=['construction','baseAbilities','gather'].includes(route)?'city':['characters','foundation','progress','alliance'].includes(route)?'embers':'battlefield';");fs.writeFileSync('public/app.js',app);
let html=fs.readFileSync('public/index.html','utf8').replace('href="construction.css">','href="construction.css"><link rel="stylesheet" href="world-theme.css">');fs.writeFileSync('public/index.html',html);
